### ISSUE TITLE
请问可否以 vendor 形式提供网关服务？

### ISSUE THREAD

**Issue by benhuang1024** [2723659854/port-mapping#1]
你好，请问可否以 vendor 形式提供网关服务？
这样方便拓展和进行揉合 workerman 后续的迭代

**Comment by 2723659854** [comment]
可以的，等一下的，这几天在写发送邮件服务

**Comment by 2723659854** [comment]
> 你好，请问可否以 vendor 形式提供网关服务？ 这样方便拓展和进行揉合 workerman 后续的迭代

可以的，等一下的，这几天在搞其他的

**Comment by benhuang1024** [comment]
收到，这个很酷；
如果有需要我进行协助的内容,可以@我

**Comment by 2723659854** [comment]
> 收到，这个很酷； 如果有需要我进行协助的内容,可以@我

好的呢，你如果比较急，你可以fork一个分支，自己弄一个扩展包。我现在在搞其他项目

**Comment by benhuang1024** [comment]
> > 收到，这个很酷； 如果有需要我进行协助的内容,可以@我
> 
> 好的呢，你如果比较急，你可以fork一个分支，自己弄一个扩展包。我现在在搞其他项目

got it，我将参考你的实现，若有引用将会声明作者
